integrated the login modal into the index page, added new pages, and …
mildredfakoya/ProjectIntern01 pull request #11
Opened 2024-02-23 22:41 UTC by nickeybamby

…updated a few codes. Index2 is a dummy page that is used for illustrative purposes to show a screen before logging in and after

2024-02-25 15:36 UTC, adieddygit requested changes, later dismissed

2024-02-25 15:36 UTC, adieddygit commented on css/eval_assessment.css
good, but the eval_assessment.php file is empty even though there is a .css and .js file for it.

2024-02-25 15:36 UTC, adieddygit commented on eval_assessment.php
empty file

2024-02-25 15:36 UTC, adieddygit commented on nav.php
please need to add the appointment_vitals.css file link to the css file links

2024-02-27 15:11 UTC, edykab approved these changes

2024-02-27 15:13 UTC, edykab approved these changes

2024-02-27 15:14 UTC, merged