updated appointment and vital signs files
mildredfakoya/ProjectIntern01 pull request #4
Opened 2024-02-17 00:42 UTC by adieddygit

Updated the Appointment and Vital signs files

2024-02-18 08:34 UTC, mildredfakoya requested changes
Consider the comment from each section and update your code as much as possible to meet the standards. For areas where the code cannot be updated, justify with reasons as a response to the comments.

2024-02-18 08:34 UTC, mildredfakoya commented on appoint_register.php
> +           <a class="nav-link" href="#">210775</a>
Why is this not a readable name but a number?

2024-02-18 08:34 UTC, mildredfakoya commented on css/appointment.css
This is good but when building a new app. Alway consider making your CSS take a mobile first approach. Great Job. But you can rewatch part 2 to get a depth of the breakpoints

2024-02-18 08:34 UTC, mildredfakoya commented on css/appointment.css
> +  /* Small devices (portrait tablets and large phones, 600px and up)*/
Try putting a condition here for when e.g (min-width:600px and max-width : 768px)to ensure that you are not overlapping breakpoints. Research this to see the best approach.

2024-02-18 08:34 UTC, mildredfakoya commented on css/vitalsigns.css
Why not make universal styles on a common css file and only put styles specific to a page on a new style sheet. For instance all your grid view and general responsiveness startup styles should have been on a css file to be included in all your pages and then page specific style on their individual style sheet and include but external files. You want to eliminate duplicate code as much as possible.

2024-02-18 17:29 UTC, adieddygit commented
Good afternoon, please have made some updates on the requested change in
previous commits

On Sun, Feb 18, 2024 at 8:34 AM Mildred Fakoya ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> Consider the comment from each section and update your code as much as
> possible to meet the standards. For areas where the code cannot be updated,
> justify with reasons as a response to the comments.
> ------------------------------
>
> In appoint_register.php
> <https://github.com/mildredfakoya/ProjectIntern01/pull/4#discussion_r1493651337>
> :
>
> > @@ -0,0 +1,77 @@
> +<?php
> +  require_once "nav.php";
> + ?>
> +
> +<body>
> +<div class="a_appoint">
> +   <h1>Appointment Registration Form</h1>
> +       <nav>
> +           <a class="nav-link" href="#">Record ID</a>
> +           <a class="nav-link" href="#">210775</a>
>
> Why is this not a readable name but a number?
> ------------------------------
>
> On css/appointment.css
> <https://github.com/mildredfakoya/ProjectIntern01/pull/4#discussion_r1493662838>
> :
>
> This is good but when building a new app. Alway consider making your CSS
> take a mobile first approach. Great Job. But you can rewatch part 2 to get
> a depth of the breakpoints
> ------------------------------
>
> In css/appointment.css
> <https://github.com/mildredfakoya/ProjectIntern01/pull/4#discussion_r1493670973>
> :
>
> > +  }
> +
> +  .col-10 {
> +    width: 83.33%;
> +  }
> +
> +  .col-11 {
> +    width: 91.66%;
> +  }
> +
> +  .col-12 {
> +    width: 100%;
> +  }
> +  }
> +
> +  /* Small devices (portrait tablets and large phones, 600px and up)*/
>
> Try putting a condition here for when e.g (min-width:600px and max-width :
> 768px)to ensure that you are not overlapping breakpoints. Research this to
> see the best approach.
> ------------------------------
>
> On css/vitalsigns.css
> <https://github.com/mildredfakoya/ProjectIntern01/pull/4#discussion_r1493671807>
> :
>
> Why not make universal styles on a common css file and only put styles
> specific to a page on a new style sheet. For instance all your grid view
> and general responsiveness startup styles should have been on a css file to
> be included in all your pages and then page specific style on their
> individual style sheet and include but external files. You want to
> eliminate duplicate code as much as possible.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/mildredfakoya/ProjectIntern01/pull/4#pullrequestreview-1887115796>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A6TEV7PAP7GV2XEV7PLQDVLYUG4JBAVCNFSM6AAAAABDM3ILGSVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTQOBXGEYTKNZZGY>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-02-19 20:36 UTC, mildredfakoya approved these changes

2024-02-19 20:36 UTC, merged